name: .NET

on:
  push:
    branches: [ "master", "fix-*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: pre-build.ps1
      run: powershell -ExecutionPolicy Unrestricted ./pre-build.ps1
      shell: pwsh
    - name: build.ps1
      run: powershell -ExecutionPolicy Unrestricted ./build.ps1
      shell: pwsh
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1.3
    - name: msbuild panacea
      run: |
        msbuild OpenKh.Research.Panacea\OpenKh.Research.Panacea.vcxproj /p:Configuration=Release /p:Platform=x64
        xcopy "OpenKh.Research.Panacea\Release\*.dll" bin\
        xcopy "OpenKh.Research.Panacea\Dependencies\*.dll" bin\
    
    - name: create openkh-release
      shell: bash
      env:
        RELEASE_TAG: "release2-${{github.run_number}}"
      run: |
        echo $RELEASE_TAG > bin/openkh-release
    
    - name: bin â†’ openkh
      run: ren bin openkh
      shell: pwsh
    - name: zip
      uses: TheDoctor0/zip-release@0.6.2
      with:
        filename: openkh.zip
        path: openkh

    - name: "GitHub release latest"
      if: ${{ github.ref_name == 'master' }}
      uses: "marvinpinto/action-automatic-releases@latest"
      continue-on-error: true # at non master branch this will always fail
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "OpenKh Latest Build"
        files: |
          openkh.zip

    - name: "GitHub release numbered"
      uses: "marvinpinto/action-automatic-releases@latest"
      continue-on-error: true # at non master branch this will always fail
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "release2-${{github.run_number}}"
        prerelease: false
        title: "OpenKh Build ${{github.run_number}} (${{github.ref_name}})"
        files: |
          openkh.zip
